- name: Intro to playbook
  hosts: all
  tasks:
    - name: Priting helloo
      ansible.builtin.debug:
        msg: Hello
    - name: priting hello through new collection
      debug:
        msg: hello throgh old module